=pod

=head1 lorito opcode definitions

=begin verify_begin

=end verify_begin

=head2 Execution Ops

=head3 noop

=over

=item Registers

None

=item Description

Do nothing.  Waste a cycle.

=back

=head3 end

=item Registers

None

=item Description

Stop the interperter, cleanly.

=head3 add

=item Registers

$dest, $src1, $src2

=item Description

Add $src1 and $src2 and store result in $dest.

=head3 sub

=item Registers

$dest, $src1, $src2

=item Description

Subtract $src1 and $src2 and store result in $dest.

=head3 mul

=head3 div

=head3 mod

=head3 and

=head3 or

=head3 xor

=head3 not

=head3 shl

=head3 shr

=head2 Comparison Ops

=head3 iseq

=head3 isgt

=head3 isge

=head2 Flow Control Ops

=head3 goto

=head3 if

=head2 Register Manipulation Ops

=head3 set

=head3 load_const

=head3 load_imm

=head3 coerce_int

=item Registers

$dest, INT($src1)

=item Description

Convert the int in $src1 into the form of $dest and stores the result into
$dest.

=item Example

  $P1 = PMC COERCE_INT $I1;

$P1 will contain a boxed integer.

=head3 coerce_num

=head3 coerce_str

=head2 PMC Ops

=head3 new

=head3 store

=head3 load

=head3 push_arg

=head3 pop_arg

=head3 cnt_arg

=head3 call

=head3 push_ret

=head3 pop_ret

=head3 cnt_ret

=head3 lookup

=head3 ctx

=head3 new_ctx

=head3 block

=head2 Environment Ops

=head3 loadlib

=head3 read

=head3 write

=head3 say

=head3 gripe

=head2 These Ops

=head3 hcf

=begin verify_end

=end verify_end
